<a href="https://colab.research.google.com/github/ClaretWheel1481/Artificial-Intelligence/blob/main/Torch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

创建一个全零的 5*5 张量

In [ ]:
torch.zeros(5,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

创建一个从 1 到 10 的张量，并将其调整为2*5的矩阵

In [ ]:
torch.arange(1,11).reshape(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

创建一个形状为(4,3)的单位矩阵

In [ ]:
torch.eye(4,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

创建一个形状为(3,3)的常数张量，值为7

In [6]:
torch.full((3,3),7)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

使用 torch.ones_like() 创建与另一个张量相同形状的全 1 张量

In [8]:
tensor = torch.tensor([[1,2],[3,4]])
torch.ones_like(tensor)

tensor([[1, 1],
        [1, 1]])

创建一个从 0 到 1 的 3*3随机张量

In [9]:
torch.rand(3,3)

tensor([[0.6157, 0.9276, 0.9148],
        [0.0980, 0.2432, 0.1101],
        [0.8873, 0.8008, 0.0793]])

使用torch.full() 创建一个填充常数值的张量

In [10]:
torch.full((2,2),5)

tensor([[5, 5],
        [5, 5]])

创建一个大小为(3,2)的张量，并将其填充成一个等差数列

In [11]:
torch.arange(6).reshape(3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

使用torch.arange()创建一个包含10个数字的张量，步长为2

In [12]:
torch.arange(0,20,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

提取张量第二行的所有元素

In [13]:
tensor = torch.tensor([[1,2],[3,4],[5,6]])
tensor[1,:]

tensor([3, 4])

提取张量的最后一列

In [14]:
tensor = torch.tensor([[1,2],[3,4],[5,6]])
tensor[:,-1]

tensor([2, 4, 6])

使用索引修改张量中第二行的第三个元素

In [20]:
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor[1,2] = 10
tensor

tensor([[ 1,  2,  3],
        [ 4,  5, 10],
        [ 7,  8,  9]])

获取张量前两列

In [21]:
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor[:,:2]

tensor([[1, 2],
        [4, 5],
        [7, 8]])

使用负索引提取张量最后一行

In [22]:
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor[-1,:]

tensor([7, 8, 9])

使用条件索引提取张量中所有大于0的元素

In [23]:
tensor = torch.tensor([1,-2,3,4,-5])
tensor[tensor>0]

tensor([1, 3, 4])

使用 torch.index_select() 从张量中选取指定的行

In [25]:
tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])
torch.index_select(tensor,0,torch.tensor([0,2]))

tensor([[1, 2],
        [5, 6]])

获取张量第一个维度的所有奇数索引的元素

In [27]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor[1::2]

tensor([2, 4, 6])

矩阵除法

In [29]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
torch.mm(a,b)

tensor([[19, 22],
        [43, 50]])

张量点积

In [30]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
torch.dot(a,b)

tensor(32)

张量标准差

In [31]:
tensor = torch.tensor([1,2,3,4,5],dtype = torch.float32)
torch.std(tensor)

tensor(1.5811)

计算张量的转置

In [33]:
tensor = torch.tensor([[1,2],[3,4]])
tensor.T

tensor([[1, 3],
        [2, 4]])