<a href="https://colab.research.google.com/github/ClaretWheel1481/Artificial-Intelligence/blob/main/Torch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

创建一个全零的 5*5 张量

In [ ]:
torch.zeros(5,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

创建一个从 1 到 10 的张量，并将其调整为2*5的矩阵

In [ ]:
torch.arange(1,11).reshape(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

创建一个形状为(4,3)的单位矩阵

In [ ]:
torch.eye(4,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

创建一个形状为(3,3)的常数张量，值为7

In [6]:
torch.full((3,3),7)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

使用 torch.ones_like() 创建与另一个张量相同形状的全 1 张量

In [8]:
tensor = torch.tensor([[1,2],[3,4]])
torch.ones_like(tensor)

tensor([[1, 1],
        [1, 1]])

创建一个从 0 到 1 的 3*3随机张量

In [9]:
torch.rand(3,3)

tensor([[0.6157, 0.9276, 0.9148],
        [0.0980, 0.2432, 0.1101],
        [0.8873, 0.8008, 0.0793]])

使用torch.full() 创建一个填充常数值的张量

In [10]:
torch.full((2,2),5)

tensor([[5, 5],
        [5, 5]])

创建一个大小为(3,2)的张量，并将其填充成一个等差数列

In [11]:
torch.arange(6).reshape(3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

使用torch.arange()创建一个包含10个数字的张量，步长为2

In [12]:
torch.arange(0,20,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])